services:
  app:
    build: .
    container_name: vetlliga-app
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      ADMIN_PASSWORD: changeme
      JWT_SECRET: changeme
      UPLOAD_DIR: /data
      DB_URL: mariadb:3306
    volumes:
      - ./data:/data
    networks:
      - app-network

  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: vetlliga
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PMA_HOST=mariadb
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - "8008:80"
    networks:
      - app-network
    depends_on:
      - mariadb

volumes:
  mariadb_data:

networks:
  app-network:
    external: true
