spring.application.name=refugiservice
# Database connection settings
spring.datasource.url=jdbc:mariadb://mariadb:3306/vetlliga
spring.datasource.username=user
spring.datasource.password=password

# Hibernate settings (optional)
spring.jpa.hibernate.ddl-auto=update