spring.application.name=refugiservice

# Database connection settings
spring.datasource.url=jdbc:mariadb://mariadb:3306/vetlliga
spring.datasource.username=user
spring.datasource.password=password

management.endpoints.web.exposure.include=health,info

spring.jpa.hibernate.ddl-auto=update

# Increase timout to wait until mariadb container is really up
spring.datasource.hikari.initialization-fail-timeout=30000
spring.datasource.hikari.connection-timeout=30000

# Admin user credentials #changeme
app.initial.admin-username=admin
app.initial.admin-password=${ADMIN_PASSWORD:}

# JWT
app.jwt.secret=${JWT_SECRET:}

# Data upload
app.upload.dir=${UPLOAD_DIR:}